# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(500, 300)
        Frame.setMinimumSize(QtCore.QSize(500, 300))
        Frame.setMaximumSize(QtCore.QSize(500, 300))
        Frame.setStyleSheet("QFrame{background-color: rgb(255, 255, 255,0.3);}\n"
"QLabel{\n"
"font-size: 18px;\n"
"}\n"
"QLineEdit{\n"
"font-size: 18px;\n"
"padding: 4px;\n"
"color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_41 = QtWidgets.QFrame(Frame)
        self.frame_41.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_41.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0, 0.2);")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_46 = QtWidgets.QFrame(self.frame_41)
        self.frame_46.setStyleSheet("background-color: rgb(0, 0, 0,0);")
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_52 = QtWidgets.QLabel(self.frame_46)
        self.label_52.setMinimumSize(QtCore.QSize(120, 120))
        self.label_52.setMaximumSize(QtCore.QSize(120, 120))
        self.label_52.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_52.setText("")
        self.label_52.setPixmap(QtGui.QPixmap("icons/girl.png"))
        self.label_52.setScaledContents(True)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_19.addWidget(self.label_52)
        self.horizontalLayout_21.addWidget(self.frame_46)
        self.frame_42 = QtWidgets.QFrame(self.frame_41)
        self.frame_42.setStyleSheet("QLabel{\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_31 = QtWidgets.QFrame(self.frame_42)
        self.frame_31.setStyleSheet("background-color: none;")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(6)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_50 = QtWidgets.QLabel(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_31.addWidget(self.label_50)
        self.copy_phone_9 = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_phone_9.sizePolicy().hasHeightForWidth())
        self.copy_phone_9.setSizePolicy(sizePolicy)
        self.copy_phone_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_phone_9.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.copy_phone_9.setStyleSheet("QPushButton{\n"
"padding: 6px 6px;\n"
"background-color: rgb(255, 163, 72);\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(163, 255, 72);\n"
"}\n"
"")
        self.copy_phone_9.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icons/check-active.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icons/check-active.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("icons/check-active.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icons/check-active.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.copy_phone_9.setIcon(icon)
        self.copy_phone_9.setObjectName("copy_phone_9")
        self.horizontalLayout_31.addWidget(self.copy_phone_9)
        self.verticalLayout_18.addWidget(self.frame_31)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_42)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_18.addWidget(self.lineEdit_19)
        self.frame_32 = QtWidgets.QFrame(self.frame_42)
        self.frame_32.setStyleSheet("background-color: none;")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(6)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_60 = QtWidgets.QLabel(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_32.addWidget(self.label_60)
        self.copy_phone_10 = QtWidgets.QPushButton(self.frame_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_phone_10.sizePolicy().hasHeightForWidth())
        self.copy_phone_10.setSizePolicy(sizePolicy)
        self.copy_phone_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.copy_phone_10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.copy_phone_10.setStyleSheet("QPushButton{\n"
"padding: 6px 6px;\n"
"background-color: rgb(255, 163, 72);\n"
"}\n"
"QPushButton:focus{\n"
"background-color: rgb(163, 255, 72);\n"
"}\n"
"")
        self.copy_phone_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("icons/check-active.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.copy_phone_10.setIcon(icon1)
        self.copy_phone_10.setObjectName("copy_phone_10")
        self.horizontalLayout_32.addWidget(self.copy_phone_10)
        self.verticalLayout_18.addWidget(self.frame_32)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_42)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_18.addWidget(self.lineEdit_20)
        self.horizontalLayout_21.addWidget(self.frame_42)
        self.verticalLayout.addWidget(self.frame_41)
        self.frame_23 = QtWidgets.QFrame(Frame)
        self.frame_23.setStyleSheet("background-color: none;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"color: red;\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"color: black;\n"
"border: 2px solid red;\n"
"color: red;\n"
"    background-color: rgb(0, 0, 0,0.3);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"border-color: none;\n"
"color: black;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(159, 11, 179, 255), stop:0.394089 rgba(255, 59, 194, 255), stop:1 rgba(255, 5, 0, 255));\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_23.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_23)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font-size: 20px;\n"
"color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.227, x2:1, y2:0.739, stop:0 rgba(0, 255, 0, 255), stop:0.507389 rgba(0, 255, 255, 255), stop:1 rgba(0, 56, 255, 255));\n"
"border: 2px solid rgb(0,0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"border-color:  black;\n"
"    background-color: rgb(0, 255, 77);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_23.addWidget(self.pushButton_12)
        self.verticalLayout.addWidget(self.frame_23)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_50.setText(_translate("Frame", "Ism familiya"))
        self.lineEdit_19.setText(_translate("Frame", "Kindur"))
        self.label_60.setText(_translate("Frame", "Login"))
        self.lineEdit_20.setText(_translate("Frame", "zsegdh"))
        self.pushButton_11.setText(_translate("Frame", "O\'chirish"))
        self.pushButton_12.setText(_translate("Frame", "Saqlash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
